### ISSUE TITLE
Table heading borders in OS X 10.9

### ISSUE THREAD

**Issue by monkeypox8** [pornel/ImageOptim#97] opened 2015-08-07 13:54 UTC
App v1.6.1a1 displays a thick, 2-3px black border surrounding the table headers post-optimization. Does not display on app startup.

![imageoptim](https://cloud.githubusercontent.com/assets/816579/9137180/fb4234f8-3ce9-11e5-9745-cf0643ee0f5f.png)

**Comment by pornel** [comment] 2015-08-07 17:42
Does it happen in a previous version as well?

**Comment by monkeypox8** [comment] 2015-08-10 13:03
Yes, I was having the same issue in 1.6 (I believe) prior to using the alpha.

**Comment by fulldecent** [comment] 2015-10-27 17:23
I am not able to reproduce this.

**Comment by pornel** [comment] 2015-11-23 15:18
I think it's fixed in 1.6.1: https://imageoptim.com/changelog.html

**Closed by pornel** 2015-11-23 15:18 UTC
